name: malware_guard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  bloc: ^8.1.1
  permission_handler: ^11.0.1
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  table_sticky_headers: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  multi_dropdown: ^2.1.4
  preload_page_view: ^0.2.0
  dropdown_search: ^5.0.6
  meta: ^1.11.0
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
